insert into "public".days("id","name", "date") values(1,'пн', '01-01-2021');
insert into "public".days("id","name", "date") values(2,'вт', '01-01-2021');
insert into "public".days("id","name", "date") values(3,'ср', '01-01-2021');
insert into "public".days("id","name", "date") values(4,'чт', '01-01-2021');
insert into "public".days("id","name", "date") values(5,'пт', '01-01-2021');
insert into "public".days("id","name", "date") values(6,'сб', '01-01-2021');

insert into "public".subjects (day_name, name) values ('пн', 'ИТЦП');
insert into "public".subjects (day_name, name) values ('пн', 'Физ-ра');
insert into "public".subjects (day_name, name) values ('пн', 'ВССиТ');
insert into "public".subjects (day_name, name) values ('пн', 'ТСИС');
insert into "public".subjects (day_name, name) values ('вт', 'ООП');
insert into "public".subjects (day_name, name) values ('вт', 'История');
insert into "public".subjects (day_name, name) values ('ср', 'Англ');
insert into "public".subjects (day_name, name) values ('ср', 'Дискретка');
insert into "public".subjects (day_name, name) values ('чт', 'Матан');
insert into "public".subjects (day_name, name) values ('чт', 'Алгем');
insert into "public".subjects (day_name, name) values ('чт', 'Физ-ра');
insert into "public".subjects (day_name, name) values ('пт', 'Прога');
insert into "public".subjects (day_name, name) values ('пт', 'ВССиТ');
insert into "public".subjects (day_name, name) values ('пт', 'Матан');
insert into "public".subjects (day_name, name) values ('пт', 'Дискретка');